name: Reply to Instagram Comments

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        env:
            INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
            INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
            GEMINI_API_KEY_INSTAGRAM: ${{ secrets.GEMINI_API_KEY_INSTAGRAM }}
            SUPABASE_URL_INSTAGRAM: ${{ secrets.SUPABASE_URL_INSTAGRAM }}
            SUPABASE_KEY_INSTAGRAM: ${{ secrets.SUPABASE_KEY_INSTAGRAM }}
            API_VERSION_INSTAGRAM: ${{ secrets.API_VERSION_INSTAGRAM }}
            BASE_URL_INSTAGRAM: ${{ secrets.BASE_URL_INSTAGRAM }}
        run: python3 reply_instagram.py